### ISSUE TITLE
error while running your project 

### ISSUE THREAD

**Issue by ansari-saif** [Kludex/awesome-fastapi-projects#19]
stack trace

Traceback (most recent call last):
  File "generate_table.py", line 31, in <module>
    writer.value_matrix = [
  File "generate_table.py", line 32, in <listcomp>
    [format_with_link(project), ", ".join(filter_list(dependencies))]
  File "generate_table.py", line 22, in format_with_link
    links = open("unique_links.txt", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'unique_links.txt'

**Comment by Li0329** [comment]
他都没上传unique_links.txt，当然报错啊
